# Define the horsepower of the engine
horsepower = 500  ### condition: 'horsepower': {'type': 'int', '<=': None, '>=': 0, 'science_constant': False, 'direct_from_question': True}
# Define the conversion factor from horsepower to kilowatts
hp_to_kw_conversion = 1.36  ### condition: 'hp_to_kw_conversion': {'type': 'float', '<=': None, '>=': 0, 'science_constant': False, 'direct_from_question': True}
# Calculate the power in kilowatts
power_kw = horsepower / hp_to_kw_conversion  ### condition: 'power_kw': {'type': 'float', '<=': None, '>=': 0, 'science_constant': False, 'direct_from_question': False}
# Round the result to the nearest kilowatt
power_kw_rounded = round(power_kw)  ### condition: 'power_kw_rounded': {'type': 'int', '<=': None, '>=': 0, 'science_constant': False, 'direct_from_question': False}
# Print the power in kilowatts
print(f"The power generated by the engine in kilowatts is: {power_kw_rounded} kW")